version: "3.9"

services:
  food-app:
    build:
      context: .
    container_name: my_food
    ports:
      - "80:80"
    restart: always
    depends_on:
      - mongodb
    networks:
      - mynetwork



  mongodb:
    image: mongo:latest
    container_name: my_mongo
    env_file:
      - .env
    ports: 
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - mynetwork
  


  redis:
    image: redis:latest
    container_name: my_redis
    ports: 
      - "6379:6379"
    networks: 
      - mynetwork

volumes:
  mongo-data:
networks:
  mynetwork:
